"""OmniRun sandbox tools for LlamaIndex agents."""

from __future__ import annotations

import shlex

from llama_index.core.tools import FunctionTool
from omnirun import Sandbox


class OmniRunToolSpec:
    """OmniRun sandbox tools for LlamaIndex agents.

    Provides four tools that share a single sandbox instance:
    - omnirun_execute: run Python code
    - omnirun_shell: run shell commands
    - omnirun_write_file: write files to the sandbox
    - omnirun_read_file: read files from the sandbox

    Each sandbox runs its own Linux kernel with hardware-level isolation,
    making it safe to execute untrusted code generated by LLMs.
    """

    def __init__(self, template: str = "python-3.11", timeout: int = 30) -> None:
        self.template = template
        self.timeout = timeout
        self._sandbox: Sandbox | None = None

    def _get_sandbox(self) -> Sandbox:
        if self._sandbox is None:
            self._sandbox = Sandbox.create(self.template, timeout=300)
        return self._sandbox

    def execute_code(self, code: str) -> str:
        """Execute Python code in an isolated Firecracker microVM sandbox. Returns stdout and stderr."""
        sb = self._get_sandbox()
        result = sb.commands.run(
            f"python3 -c {shlex.quote(code)}", timeout=self.timeout
        )
        output = ""
        if result.stdout:
            output += result.stdout
        if result.stderr:
            output += f"\nSTDERR: {result.stderr}"
        if result.exit_code != 0:
            output += f"\nExit code: {result.exit_code}"
        return output or "(no output)"

    def run_shell(self, command: str) -> str:
        """Run a shell command in the sandbox (install packages, list files, etc.)."""
        sb = self._get_sandbox()
        result = sb.commands.run(command, timeout=60)
        output = result.stdout or ""
        if result.stderr:
            output += f"\nSTDERR: {result.stderr}"
        return output or "(no output)"

    def write_file(self, path: str, content: str) -> str:
        """Write a file to the sandbox filesystem."""
        sb = self._get_sandbox()
        sb.files.write(path, content)
        return f"Written {len(content)} bytes to {path}"

    def read_file(self, path: str) -> str:
        """Read a file from the sandbox filesystem."""
        sb = self._get_sandbox()
        return sb.files.read(path)

    def to_tool_list(self) -> list[FunctionTool]:
        """Return all OmniRun tools as a list of LlamaIndex FunctionTools."""
        return [
            FunctionTool.from_defaults(
                fn=self.execute_code,
                name="omnirun_execute",
                description="Execute Python code in an isolated Firecracker microVM sandbox",
            ),
            FunctionTool.from_defaults(
                fn=self.run_shell,
                name="omnirun_shell",
                description="Run a shell command in the sandbox",
            ),
            FunctionTool.from_defaults(
                fn=self.write_file,
                name="omnirun_write_file",
                description="Write a file to the sandbox",
            ),
            FunctionTool.from_defaults(
                fn=self.read_file,
                name="omnirun_read_file",
                description="Read a file from the sandbox",
            ),
        ]

    def cleanup(self) -> None:
        """Kill the sandbox and release resources."""
        if self._sandbox is not None:
            self._sandbox.kill()
            self._sandbox = None
